### PR TITLE
Fix support for setting color scheme manually 

### LINKED ISSUE #1548: Colors.setScheme works fine for Views but not for Text
### Describe the bug
Trying to change the theme at runtime using Colors.setScheme works fine for View background, but not for Text color.

### To Reproduce
0. Create a new react native App
1. Use Colors.loadSchemes to create 'light' and 'dark' themes with screenBG and textColor properties, with values for both themes.
2. Create a View (with bg-screenBG) that contains a Text (with textColor) and a Switch to modify the Theme at runtime.
3. On the switch OnValueChange event, change a state variable that determines the theme and eventually call Colors.setScheme choosing one theme or the other depending on that state variable.
4. While running the app use the switch and you'll see the View changing it's color but not the Text

### Expected behavior
The Text componen should also adapt to the newly set scheme

### Device (please complete the following information)
 - Android emulator
 - OS: Windows 10 + Powershell

### Code sample
```
Colors.loadSchemes({
  light: {
    screenBG: Colors.white,
    textColor: Colors.grey10,
  },
  dark: {
    screenBG: Colors.grey10,
    textColor: Colors.white,
  },
});

const setTheme = (dark: boolean): void => {
  Colors.setScheme(dark ? 'dark' : 'light');
};

const App = () => {
  const [darkTheme, setDarkTheme] = useState(false);

  setTheme(darkTheme);

  return (
    <View flex center bg-screenBG>
      <Text textColor text10>
        Demo
      </Text>
      <Switch value={darkTheme} onValueChange={value => setDarkTheme(value)} />
    </View>
  );
};
```

### Additional context
Both themes display properly if I manually change the value of the state property and refresh.

Additionally the application does not react to a change in the Theme in Android settings like the libraries' Demo application does. I don't know if this is an issue or if there is something not documented to be done. I can raise a separate bug for this if necessary?

### PR DESCRIPTION
**Pull request by ethanshar**
## Description
Fix support for setting color scheme manually (Fix #1548)
- Created Scheme class to handle all schemes logic 
- Move relevant logic from Colors class to Scheme class
- Change appearance change registration in asBaseComponent with scheme change registration
- Update DarkModeScreen example to showcase a scenario of manual scheme change

## Changelog
Fix support for setting color scheme manually

### CODE REVIEW

File: demo/src/screens/foundationScreens/DarkModeScreen.tsx [hunk 1]
```diff
@@ -1,22 +1,46 @@
 import React, {Component} from 'react';
 import {StyleSheet} from 'react-native';
-import {View, Text, Constants} from 'react-native-ui-lib';
+import {View, Text, Colors, Constants, SegmentedControl, SegmentedControlItemProps} from 'react-native-ui-lib';
```
Comment (lidord-wix) [inline demo/src/screens/foundationScreens/DarkModeScreen.tsx:3]: `SegmentedControlItemProps` is imported but not used

File: demo/src/screens/foundationScreens/DarkModeScreen.tsx [hunk 2]
```diff
@@ -1,22 +1,46 @@
...
 
 class DarkModeScreen extends Component {
-  state = {};
+  state = {
+    selectedSchemeType: 'default'
+  };
+
+  changeSchemeType = (index: number) => {
+    this.setState({selectedSchemeType: SCHEME_TYPES[index].value});
+    Colors.setScheme(SCHEME_TYPES[index].value);
```
Comment (lidord-wix) [inline demo/src/screens/foundationScreens/DarkModeScreen.tsx:23]: There's a ts error here - it requires declaring the type at the `SCHEME_TYPES` array

**Review by lidord-wix — COMMENTED** [review]
Very Cool!
I left few small comments :)

File: src/style/__tests__/scheme.spec.js [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+    });
+
+    it('should unregister scheme change listener', () => {
+      const listener = jest.fn();
+      Scheme.addSchemeChangeListener(listener);
+      Scheme.setScheme('dark');
+      expect(listener).toHaveBeenCalledTimes(1);
+      Scheme.removeSchemeChangeListener(listener);
+      Scheme.setScheme('light');
+      expect(listener).toHaveBeenCalledTimes(1);
```
[the remark this answers is not in the document]
Comment (ethanshar) [reply src/style/__tests__/scheme.spec.js:82]: We expect the count of calls to stay 1 (instead of 2) 
`toHaveBeenCalledTimes(x);` checks the total calls of a function during this test iteration

If you'll comment this line ->  `Scheme.removeChangeListener(listener);`
You'll see the count will be 2

File: src/style/__tests__/scheme.spec.js [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+    });
+
+    it('should not be triggered if scheme set to the same type', () => {
+      const listener = jest.fn();
+      Scheme.addSchemeChangeListener(listener);
+      Scheme.setScheme('dark');
+      expect(listener).toHaveBeenCalledTimes(1);
+      Scheme.setScheme('dark');
+      expect(listener).toHaveBeenCalledTimes(1);
```
[the remark this answers is not in the document]
Comment (ethanshar) [reply src/style/__tests__/scheme.spec.js:91]: See my previous comment. 
It's exactly the same thing.

File: src/style/__tests__/scheme.spec.js [hunk 5]
```diff
@@ -0,0 +1,94 @@
...
+      Scheme.setScheme('dark');
+      expect(Scheme.getSchemeType()).toBe('dark');
+    });
+
+    it('should throw on invalid scheme color', () => {
+      expect(() => Scheme.setScheme('yellow')).toThrow(`yellow is invalid colorScheme, please use 'light' | 'dark' | 'default'`);
+    });
+  });
+
+  describe('getScheme/loadScheme', () => {
```
[the remark this answers is not in the document]
Comment (ethanshar) [reply src/style/__tests__/scheme.spec.js:36]: Added a test and fixed code to actually throw an error (And not just `console.error`)

File: demo/src/screens/foundationScreens/DarkModeScreen.tsx (hunk 1 above)
Comment (ethanshar) [reply demo/src/screens/foundationScreens/DarkModeScreen.tsx]: Fixed

File: demo/src/screens/foundationScreens/DarkModeScreen.tsx (hunk 2 above)
Comment (ethanshar) [reply demo/src/screens/foundationScreens/DarkModeScreen.tsx:23]: Fixed

**Review by lidord-wix — APPROVED** [review]
