### PR TITLE
Picker - multi select - fix behavior when the value is changed by user

### LINKED ISSUE #2005: Picker Value, State not listening.
## Description

I need to clear the Picker value. but state is not listening.

### Related to

- [x] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Code snippet

```
<Picker
    value={recipients}
    onChange={(itemValue) => {setRecipients(itemValue)}}
    mode={Picker.modes.MULTI}
    migrateTextField
    migrate
    showSearch    
  >
  {options.map(item => (
    <Picker.Item key={item.value} value={item.value} label={item.label} />
  ))}
</Picker>

setRecipients([]) - not working.
```

### Environment

- React Native: 0.68.1
- React Native UI Lib: 6.13.3

### Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

### PR DESCRIPTION
**Pull request by M-i-k-e-l**
## Description
Picker - multi select - fix behavior when the value is changed by user
Fixes #2005

## Changelog
Picker - multi select - fix behavior when the value is changed by user

### CODE REVIEW

File: src/components/picker/helpers/usePickerSelection.tsx [hunk 1]
```diff
@@ -13,6 +13,13 @@ const usePickerSelection = (props: UsePickerSelectionProps) => {
   const [multiDraftValue, setMultiDraftValue] = useState(value as PickerMultiValue);
   const [multiFinalValue, setMultiFinalValue] = useState(value as PickerMultiValue);
 
+  useEffect(() => {
+    if (multiFinalValue !== value) {
```
Comment (ethanshar) [inline src/components/picker/helpers/usePickerSelection.tsx:17]: Do we always want to do this or just when the picker is in "multi" mode? 
Could this cause an issue in the "single" mode?

Comment (M-i-k-e-l) [reply src/components/picker/helpers/usePickerSelection.tsx]: I think it should not cause an issue, but it's probably more readable and will cause less renders 👍

**Review by ethanshar — APPROVED** [review]
