### PR TITLE
Fix picker value issue

### LINKED ISSUE #1387: Picker mode='MULTI' item selection not working with custom renderPicker in 5.22.0
### Describe the bug

When I use custom `renderPicker` in the `Picker` component with `mode='MULTI'` not able to select any item from the `Picker.Item` and `props.isSelected` always false.

We can reproduce in our UI lib expo examples.

```
"react-native-ui-lib": "^5.22.0",
```

It was working fine before v5.22.  and Not working in v5.27 also.

Not Working with "MULTI" and renderPicker
```
<Picker title={t('common:batches')}
  mode="MULTI"
  value={selectedStudentBatchRef.current ?? []}
  onChange={function(option: any) {
    console.log(option);
  }}
  renderPicker={function() {
    return (
      <View>
        <Button label={t('common:addBatch')} />
      </View>
    );
  }}>

...
```

Working without renderPicker
```
<Picker title={t('common:batches')}
  mode="MULTI"
  value={selectedStudentBatchRef.current ?? []}
  onChange={function(option: any) {
    console.log(option);
  }}>

...
```

_Originally posted by @saravanakumargn in https://github.com/wix/react-native-ui-lib/issues/1258#issuecomment-873763486_

### PR DESCRIPTION
**Pull request by ethanshar**
## Description
Fix how we handle internal picker value change for custom picker in multi mode

Fix #1387 

## Changelog
Fix issue with Picker with custom renderPicker in multi-select mode not reacting to value change

### CODE REVIEW

File: src/components/picker/index.js [hunk 1]
```diff
@@ -182,20 +182,21 @@ class Picker extends Component {
...
-        return {
-          value: nextProps.value
-        };
-      }
-    } else if (_.isFunction(nextProps.renderPicker) && prevState.value !== nextProps.value) {
+    /* Relevant for keeping the value prop controlled - react when user change value prop */
+    const externalValueChanged = !_.isEmpty(nextProps.value) && prevState.value !== nextProps.value;
+    /* Relevant for multi select mode when we keep an internal value state */
+    const internalValueChanged = prevState.value !== prevState.prevValue;
+    if (internalValueChanged) {
```
Comment (M-i-k-e-l) [inline src/components/picker/index.js:189]: It seems this is not actually `internal`, we get here sometimes from external change.
Code for reproduction below (change from external will work on consecutive change and not each time):
```
import _ from 'lodash';
import React, {Component} from 'react';
import {StyleSheet} from 'react-native';
import {View, Text, Card, TextField, Button, Picker, PickerItemValue} from 'react-native-ui-lib'; //eslint-disable-line

export default class PlaygroundScreen extends Component {
  render() {
    return (
      <View bg-dark80 flex padding-20 center>
        <View marginT-20>
          <TextField placeholder="Placeholder" />
        </View>
        <Card height={100} center padding-20>
          <Text text50>Playground Screen</Text>
        </Card>
        <View flex center>
          <Button marginV-20 label="Button"/>
        </View>
        <PickerBug/>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {},
});

class PickerBug extends React.Component {
  state = {
    val: 1
  };

  getNumberPickerRenderer = (label: string | undefined) => (value?: PickerItemValue) => (
    <View padding-20 row>
      <View marginR-s5 flex>
        <Text body>{label}</Text>
      </View>
      <View>
        <Text useCustomTheme bodyBold>
          {value ?? null}
        </Text>
      </View>
    </View>
  );

  numberOptions = [
    {label: '1', value: 1},
    {label: '2', value: 2},
    {label: '3', value: 3}
  ];

  render() {
    return (
      <>
        <Text>Real value: {this.state.val}</Text>
        <Button link onPress={() => this.setState({val: this.state.val + 1})} label="+"/>
        <Button link onPress={() => this.setState({val: this.state.val - 1})} label="-"/>
        <Picker
          migrate
          value={this.state.val}
          onChange={(val: number) => this.setState({val})}
          renderPicker={this.getNumberPickerRenderer('label')}
        >
          {this.numberOptions.map(item => (
            <Picker.Item key={item.value} value={item.value} label={item.label}/>
          ))}
        </Picker>
      </>
    );
  }
}
```

Comment (ethanshar) [reply src/components/picker/index.js]: Should be fixed now.

**Review by M-i-k-e-l — APPROVED** [review]
