### PR TITLE
Fix/tab controller safe area and indicator width

### LINKED ISSUE #1746: TabBar works incorrect after rotating screen
### Describe the bug

TabPage position and tab bar item's position are wrong after rotating the screen

### To Reproduce

- A TabController
- Rotate screen
- Swipe between screens

### Expected behavior

The tab page and tab bar should work properly after screen rotating 

### Code snippet

Repro Snack: https://snack.expo.dev/@likeso/delicious-french-fries

### Screenshots

image

### Device (please complete the following information)

Device: iPhone 13
OS: iOS 15

### Additional context

Anothers problem is that i cannot customize the spacing between tab bar items.
I am trying to customize the spacing between tab bar items using:`style: { paddingHorizontal: 8 },` in `TabControllerItemProps`
But i got this:
image
Is this the correct way to customize the spacing?

### PR DESCRIPTION
**Pull request by M-i-k-e-l**
## Description
TabController - support safe area and constant indicator width

## Changelog
Fixes #1746 - TabController - support safe area (useSafeArea) and constant indicator width (indicatorWidth)

### CODE REVIEW

File: src/components/tabController/index.tsx [hunk 1]
```diff
@@ -54,17 +58,24 @@ function TabController({
...
   children
 }: PropsWithChildren<TabControllerProps>) {
-  const [screenWidth, setScreenWidth] = useState<number>(Constants.windowWidth);
+
+  const getScreenWidth = () => {
+    const {left, right} = Constants.getSafeAreaInsets();
+    return Constants.windowWidth - (useSafeArea && Constants.isIphoneX ? left + right : 0);
+  };
+
+  const [screenWidth, setScreenWidth] = useState<number>(getScreenWidth());
```
Comment (ethanshar) [inline src/components/tabController/index.tsx:70]: It's a little weird the method `getScreenWidth` is above the useState. 
I suggest moving the function out of the component code, nothing fancy, it can be top/bottom of the file

Comment (M-i-k-e-l) [reply src/components/tabController/index.tsx]: Fixed

**Review by ethanshar — APPROVED** [review]
